#Para Desarrollo local#
services:
  # --- SERVICIO 1: FRONTEND (WEB) ---
  web-client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        - VITE_API_URL=http://localhost:3000
        - VITE_API_PREFIX=/ec/api/v1
    container_name: economic-client-dev
    restart: unless-stopped
    networks:
      - app_local_net
    depends_on:
      - api
    ports:
      - target: 80
        published: 5173
        protocol: tcp

  # --- SERVICIO 2: BACKEND (API) ---
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: economic-server-dev
    env_file:
      - ./.env
    restart: always
    depends_on:
      postgres-dev:
        condition: service_healthy
    networks:
      - app_local_net
    ports:
      - target: 3000
        published: 3000
        protocol: tcp

  # --- SERVICIO 3: BASE DE DATOS ---
  postgres-dev:
    image: postgres:16
    container_name: postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: leodev
      POSTGRES_PASSWORD: leodev-root
      POSTGRES_DB: developmentDB_postgres
    #PARA LOCAL DEV
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    volumes:
      - mi_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leodev -d developmentDB_postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_local_net

networks:
  app_local_net:
    driver: bridge
#PARA LOCAL DEV
volumes:
  mi_postgres_data: